// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnalyzeArticle(arg1:number,arg2:number,arg3:number):Promise<string>;

export function AnalyzeArticleWithMode(arg1:number,arg2:number,arg3:number,arg4:string):Promise<string>;

export function AskQuestion(arg1:number,arg2:number,arg3:string):Promise<number>;

export function AskQuestionFollowUp(arg1:number,arg2:number,arg3:string,arg4:number):Promise<number>;

export function BatchAnalyze(arg1:Array<number>,arg2:number,arg3:number):Promise<void>;

export function CancelAskQuestion():Promise<void>;

export function CheckAppUpdate():Promise<models.AppUpdateResult>;

export function CreateQASession(arg1:number,arg2:string):Promise<models.QASession>;

export function CreateRoleFromTemplate(arg1:string):Promise<models.Role>;

export function DebugQAPing(arg1:string):Promise<string>;

export function DeleteArticle(arg1:number):Promise<void>;

export function DeleteChannel(arg1:number):Promise<void>;

export function DeletePrompt(arg1:number):Promise<void>;

export function DeleteQAPin(arg1:number):Promise<void>;

export function DeleteQASession(arg1:number):Promise<void>;

export function DeleteRole(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DownloadAndInstallAppUpdate(arg1:string,arg2:string):Promise<string>;

export function ExportArticle(arg1:number):Promise<void>;

export function ExportBatchFailures():Promise<void>;

export function GetAnalysisDashboard():Promise<models.AnalysisDashboard>;

export function GetAnalysisDashboardByDays(arg1:number):Promise<models.AnalysisDashboard>;

export function GetAnalysisHistory(arg1:number):Promise<Array<models.AnalysisHistory>>;

export function GetAppUpdateConfig():Promise<models.AppUpdateConfig>;

export function GetAppVersion():Promise<string>;

export function GetArticle(arg1:number):Promise<models.Article>;

export function GetArticleTags(arg1:number):Promise<Array<models.Tag>>;

export function GetArticles(arg1:string,arg2:number):Promise<Array<models.Article>>;

export function GetBatchStatus():Promise<models.BatchStatus>;

export function GetChannels():Promise<Array<models.AIChannel>>;

export function GetMinerUConfig():Promise<models.MinerUConfig>;

export function GetPromptVersions(arg1:number):Promise<Array<models.PromptVersion>>;

export function GetPrompts():Promise<Array<models.Prompt>>;

export function GetQADashboard():Promise<models.QADashboard>;

export function GetQADashboardByDays(arg1:number):Promise<models.QADashboard>;

export function GetQAMessages(arg1:number):Promise<Array<models.QAMessage>>;

export function GetQAPins(arg1:number):Promise<Array<models.QAPin>>;

export function GetQASessions(arg1:number):Promise<Array<models.QASession>>;

export function GetRoleTemplates():Promise<Array<models.RoleTemplate>>;

export function GetRoles():Promise<Array<models.Role>>;

export function GetTags():Promise<Array<models.Tag>>;

export function GetTelegraphArticles(arg1:string,arg2:number,arg3:string,arg4:number):Promise<Array<models.TelegraphArticleItem>>;

export function GetTelegraphDashboard():Promise<models.TelegraphDashboard>;

export function GetTelegraphDashboardByDays(arg1:number):Promise<models.TelegraphDashboard>;

export function GetTelegraphDigests(arg1:number):Promise<Array<models.TelegraphDigest>>;

export function GetTelegraphSchedulerConfig():Promise<models.TelegraphSchedulerConfig>;

export function GetTelegraphSchedulerStatus():Promise<models.TelegraphSchedulerStatus>;

export function GetTelegraphWatchlist():Promise<Array<models.WatchStock>>;

export function ImportArticle():Promise<models.Article>;

export function ImportArticles():Promise<Array<models.Article>>;

export function OpenURL(arg1:string):Promise<void>;

export function PauseBatchAnalyze():Promise<void>;

export function RenameQASession(arg1:number,arg2:string):Promise<void>;

export function RestorePromptVersion(arg1:number,arg2:number):Promise<void>;

export function ResumeBatchAnalyze():Promise<void>;

export function RetryFailedBatchAnalyze():Promise<void>;

export function RunTelegraphSchedulerNow():Promise<void>;

export function SaveAppUpdateConfig(arg1:models.AppUpdateConfig):Promise<void>;

export function SaveChannel(arg1:models.AIChannel):Promise<void>;

export function SaveMinerUConfig(arg1:models.MinerUConfig):Promise<void>;

export function SavePrompt(arg1:models.Prompt):Promise<void>;

export function SaveQAPin(arg1:models.QAPin):Promise<models.QAPin>;

export function SaveRole(arg1:models.Role):Promise<void>;

export function SaveTag(arg1:models.Tag):Promise<void>;

export function SaveTelegraphSchedulerConfig(arg1:models.TelegraphSchedulerConfig):Promise<void>;

export function SaveTelegraphWatchlist(arg1:Array<models.WatchStock>):Promise<void>;

export function SetArticleTags(arg1:number,arg2:Array<number>):Promise<void>;

export function SetDefaultRole(arg1:number):Promise<void>;

export function StartBatchAnalyze(arg1:Array<number>,arg2:number,arg3:number,arg4:number,arg5:string):Promise<void>;

export function StopTelegraphScheduler():Promise<void>;
