// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeArticle(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeArticle'](arg1, arg2, arg3);
}

export function AnalyzeArticleWithMode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnalyzeArticleWithMode'](arg1, arg2, arg3, arg4);
}

export function AskQuestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['AskQuestion'](arg1, arg2, arg3);
}

export function AskQuestionFollowUp(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AskQuestionFollowUp'](arg1, arg2, arg3, arg4);
}

export function BatchAnalyze(arg1, arg2, arg3) {
  return window['go']['main']['App']['BatchAnalyze'](arg1, arg2, arg3);
}

export function CancelAskQuestion() {
  return window['go']['main']['App']['CancelAskQuestion']();
}

export function CreateQASession(arg1, arg2) {
  return window['go']['main']['App']['CreateQASession'](arg1, arg2);
}

export function CreateRoleFromTemplate(arg1) {
  return window['go']['main']['App']['CreateRoleFromTemplate'](arg1);
}

export function DebugQAPing(arg1) {
  return window['go']['main']['App']['DebugQAPing'](arg1);
}

export function DeleteArticle(arg1) {
  return window['go']['main']['App']['DeleteArticle'](arg1);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteQAPin(arg1) {
  return window['go']['main']['App']['DeleteQAPin'](arg1);
}

export function DeleteQASession(arg1) {
  return window['go']['main']['App']['DeleteQASession'](arg1);
}

export function DeleteRole(arg1) {
  return window['go']['main']['App']['DeleteRole'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function ExportArticle(arg1) {
  return window['go']['main']['App']['ExportArticle'](arg1);
}

export function ExportBatchFailures() {
  return window['go']['main']['App']['ExportBatchFailures']();
}

export function GetAnalysisDashboard() {
  return window['go']['main']['App']['GetAnalysisDashboard']();
}

export function GetAnalysisDashboardByDays(arg1) {
  return window['go']['main']['App']['GetAnalysisDashboardByDays'](arg1);
}

export function GetAnalysisHistory(arg1) {
  return window['go']['main']['App']['GetAnalysisHistory'](arg1);
}

export function GetArticle(arg1) {
  return window['go']['main']['App']['GetArticle'](arg1);
}

export function GetArticleTags(arg1) {
  return window['go']['main']['App']['GetArticleTags'](arg1);
}

export function GetArticles(arg1, arg2) {
  return window['go']['main']['App']['GetArticles'](arg1, arg2);
}

export function GetBatchStatus() {
  return window['go']['main']['App']['GetBatchStatus']();
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetMinerUConfig() {
  return window['go']['main']['App']['GetMinerUConfig']();
}

export function GetPromptVersions(arg1) {
  return window['go']['main']['App']['GetPromptVersions'](arg1);
}

export function GetPrompts() {
  return window['go']['main']['App']['GetPrompts']();
}

export function GetQADashboard() {
  return window['go']['main']['App']['GetQADashboard']();
}

export function GetQADashboardByDays(arg1) {
  return window['go']['main']['App']['GetQADashboardByDays'](arg1);
}

export function GetQAMessages(arg1) {
  return window['go']['main']['App']['GetQAMessages'](arg1);
}

export function GetQAPins(arg1) {
  return window['go']['main']['App']['GetQAPins'](arg1);
}

export function GetQASessions(arg1) {
  return window['go']['main']['App']['GetQASessions'](arg1);
}

export function GetRoleTemplates() {
  return window['go']['main']['App']['GetRoleTemplates']();
}

export function GetRoles() {
  return window['go']['main']['App']['GetRoles']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTelegraphArticles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTelegraphArticles'](arg1, arg2, arg3, arg4);
}

export function GetTelegraphDashboard() {
  return window['go']['main']['App']['GetTelegraphDashboard']();
}

export function GetTelegraphDashboardByDays(arg1) {
  return window['go']['main']['App']['GetTelegraphDashboardByDays'](arg1);
}

export function GetTelegraphDigests(arg1) {
  return window['go']['main']['App']['GetTelegraphDigests'](arg1);
}

export function GetTelegraphSchedulerConfig() {
  return window['go']['main']['App']['GetTelegraphSchedulerConfig']();
}

export function GetTelegraphSchedulerStatus() {
  return window['go']['main']['App']['GetTelegraphSchedulerStatus']();
}

export function GetTelegraphWatchlist() {
  return window['go']['main']['App']['GetTelegraphWatchlist']();
}

export function ImportArticle() {
  return window['go']['main']['App']['ImportArticle']();
}

export function ImportArticles() {
  return window['go']['main']['App']['ImportArticles']();
}

export function PauseBatchAnalyze() {
  return window['go']['main']['App']['PauseBatchAnalyze']();
}

export function RenameQASession(arg1, arg2) {
  return window['go']['main']['App']['RenameQASession'](arg1, arg2);
}

export function RestorePromptVersion(arg1, arg2) {
  return window['go']['main']['App']['RestorePromptVersion'](arg1, arg2);
}

export function ResumeBatchAnalyze() {
  return window['go']['main']['App']['ResumeBatchAnalyze']();
}

export function RetryFailedBatchAnalyze() {
  return window['go']['main']['App']['RetryFailedBatchAnalyze']();
}

export function RunTelegraphSchedulerNow() {
  return window['go']['main']['App']['RunTelegraphSchedulerNow']();
}

export function SaveChannel(arg1) {
  return window['go']['main']['App']['SaveChannel'](arg1);
}

export function SaveMinerUConfig(arg1) {
  return window['go']['main']['App']['SaveMinerUConfig'](arg1);
}

export function SavePrompt(arg1) {
  return window['go']['main']['App']['SavePrompt'](arg1);
}

export function SaveQAPin(arg1) {
  return window['go']['main']['App']['SaveQAPin'](arg1);
}

export function SaveRole(arg1) {
  return window['go']['main']['App']['SaveRole'](arg1);
}

export function SaveTag(arg1) {
  return window['go']['main']['App']['SaveTag'](arg1);
}

export function SaveTelegraphSchedulerConfig(arg1) {
  return window['go']['main']['App']['SaveTelegraphSchedulerConfig'](arg1);
}

export function SaveTelegraphWatchlist(arg1) {
  return window['go']['main']['App']['SaveTelegraphWatchlist'](arg1);
}

export function SetArticleTags(arg1, arg2) {
  return window['go']['main']['App']['SetArticleTags'](arg1, arg2);
}

export function SetDefaultRole(arg1) {
  return window['go']['main']['App']['SetDefaultRole'](arg1);
}

export function StartBatchAnalyze(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartBatchAnalyze'](arg1, arg2, arg3, arg4, arg5);
}

export function StopTelegraphScheduler() {
  return window['go']['main']['App']['StopTelegraphScheduler']();
}
